export const imgData = [
  { file: "rapidRabbit.png", title: "Rapid Rabbit", description: "adsdad" },
  { file: "unicorn.png", title: "Last Unicorn", description: "" },
  { file: "back.png", title: "I Am Back", description: "" },
  { file: "hood.jpg", title: "Hooded", description: "" },
  { file: "tree.png", title: "Tree of Life", description: "" },
  { file: "crackedFaces.png", title: "Fraction Agency", description: "" },
  { file: "sweets.png", title: "Sweets For The Sweet", description: "" },
  { file: "concrete_melting.png", title: "Melting Concrete", description: "" },
  { file: "hypocrites.png", title: "HypoChrist", description: "" },
  { file: "hose_face.png", title: "Hose Face", description: "" },
  { file: "turbine.png", title: "Comprehension", description: "" },
  { file: "comix_collection.png", title: "The Good Old Times", description: "" },
  { file: "time.png", title: "Time", description: "" },
  { file: "cannibal.png", title: "Ready When You Are", description: "" },
  { file: "food_chain.png", title: "Cross Dependencies", description: "" },
  { file: "outta_my_head.png", title: "Outta My Head", description: "" },
  { file: "cracked_lips.png", title: "A Cracked Smile", description: "" },
  { file: "human_land.png", title: "Pillars of Humiliation", description: "" },
  { file: "dead_god.jpg", title: "Rather Than Server In Heaven", description: "" },
  { file: "afterHours.jpg", title: "After Hours", description: "" },
  { file: "trout_on_ktm.jpg", title: "Trout On A Bike", description: "" },
  { file: "bloodQueen.jpg", title: "Blood Queen", description: "" },
  { file: "pokemongo.jpg", title: "PokeMongo", description: "" },
  { file: "bones.jpg", title: "Lie With Your Bones", description: "" },
  { file: "giveMeUrHand.jpg", title: "Give Me Your Hand", description: "" },
  { file: "hug.jpg", title: "Hug The Perversion", description: "" },
  { file: "longVisage.jpg", title: "Long Visage", description: "" },
  { file: "cyborgReaper3.jpg", title: "Ready", description: "" },
  { file: "girlAndMonstersX.jpg", title: "Me And My Monsters", description: "" },
  { file: "goForAWalk.jpg", title: "Go For A Walk", description: "" },
  { file: "fatSoldier.jpg", title: "Fat Soldier", description: "" },
  { file: "blackGirl.jpg", title: "Let It Pee", description: "" },
  { file: "cypork.jpg", title: "CyPork", description: "" },
  { file: "fairy.jpg", title: "Raise", description: "" },
  { file: "surrealWall.jpg", title: "Wall Of Insanity", description: "" },
  { file: "priest.jpg", title: "God Is With You", description: "" },
  { file: "phone.jpg", title: "Always Online", description: "" },
  { file: "spell.jpg", title: "The Spell", description: "" },
  { file: "violentine.jpg", title: "Happy Violentine's Day", description: "" },
  { file: "creep.jpg", title: "Freedom Of Expression", description: "" },
  { file: "maggots.jpg", title: "King Of Maggots", description: "" },
  { file: "spikehead.jpg", title: "Spikehead", description: "" },
  { file: "cyborgReaper2a.jpg", title: "Impending Mischief", description: "" },
  { file: "zombies.jpg", title: "Bad Situation", description: "" },
  { file: "lovers.jpg", title: "Empty Lovers", description: "" },
  { file: "antlersface.jpg", title: "Antlered Face", description: "" },
  { file: "fireball.jpg", title: "Small Miracle", description: "" },
  { file: "hair.jpg", title: "I Comb Your Hair", description: "" },
  { file: "musick.jpg", title: "Musick", description: "" },
  { file: "cyborgReaper.jpg", title: "I Got Souls", description: "" },
  { file: "conjured.jpg", title: "Cold Impression", description: "" },
  { file: "rockStar.jpg", title: "Hit The Tone", description: "" },
  { file: "xMess.jpg", title: "X-Mess", description: "" },
  { file: "twoSwords.jpg", title: "Two Swords", description: "" },
  { file: "heIsTurningBlue.jpg", title: "He Is Turning Blue", description: "" },
  { file: "toothFairy.jpg", title: "Terry The Fairy", description: "" },
  { file: "yolandi.jpg", title: "Freeky", description: "" },
  { file: "phiBot.jpg", title: "Phi-Bot", description: "" },
  { file: "greenImp.jpg", title: "Cozy Bushy Green", description: "" },
  { file: "whiteCyborg.jpg", title: "Synthetic Pale", description: "" },
  { file: "sunDevourer.jpg", title: "Sun Devourer", description: "" },
  { file: "barAside.jpg", title: "Bar Aside", description: "" },
  { file: "psychoGirls_all.jpg", title: "My Little Girls", description: "" },
  { file: "psychoGirl.jpg", title: "Insane Madeleine", description: "" },
  { file: "mAz.jpg", title: "Can I Keep him, Mom?", description: "" },
  { file: "djMike_v1.4.jpg", title: "Groove Monsters", description: "" },
  { file: "sculptured.jpg", title: "Sculptured", description: "" },
  { file: "Stairs.jpg", title: "Punish The Innocent", description: "" },
  { file: "Mage.jpg", title: "The Mage Apprentice", description: "" },
  { file: "Street.jpg", title: "Attention! High Voltage", description: "" },
  { file: "shout.jpg", title: "Post Light", description: "" },
  { file: "fleshmountains.jpg", title: "Carnal Path", description: "" },
  { file: "beautiful.jpg", title: "The Pretty Ones", description: "" },
  { file: "angelEyes.jpg", title: "Eyes Of A Fallen Angel", description: "" },
  { file: "necro.jpg", title: "Ipasou", description: "" },
  { file: "7sins.jpg", title: "Sins", description: "" },
  { file: "ugly.jpg", title: "Aren't We Beautiful?", description: "" },
  { file: "planets.jpg", title: "Draining Planets", description: "" },
  { file: "bridge2.jpg", title: "The Bridge", description: "" },
  { file: "landescape.jpg", title: "Foreign Landescape", description: "" },
  { file: "puke.jpg", title: "Conema (Commercial Enema)", description: "" },
  { file: "lizardOnTheRock.jpg", title: "Step Through A Strange World", description: "" },
  { file: "teeth.jpg", title: "Cleft Lip", description: "" },
  { file: "Contract.jpg", title: "The Contract", description: "" },
  { file: "Spoteye.jpg", title: "Spoteye", description: "" },
  {
    file: "Reaper.jpg",
    title: "Eulogy",
    description:
      "The idea of this picture was to paint the grim reaper grieving the loss of a loved one. " +
      "It's a bit ironic, as the reaper is usually the one who brings death. " +
      "The name 'Eulogy' refers is a title of a 'tool' song. " +
      "One of the gravestones hast a tribute to the deceased artist 'Moebius', who passed away in 2012." +
      "I am not happy with the look of the reaper itself, but the overall mood of the picture works for me." +
      "Especially the background I tink is quite successful for the time I did this work",
  },
  {
    file: "Mimic.jpg",
    title: "Mimic",
    description:
      "My very first digital painting made in photoshop with a wacom-board. It feels a bit historic and is a milestone in my development as an digital artist." +
      "It shows a creature with two big black eyes and a wide open mouth with cracked lips standing in front of a tiled white wall." +
      "As I remember back it started with a sketch on a paper while watching tv." +
      "The name 'Mimic' was just an idea I stole from the chest-creatures in the DnD universe, I first encountered in an Ultima game in the 90s." +
      "The picture was made in 2012 and I still like it.",
  },
];
