export const imgTitles = {
  "unicorn.png": "Last Unicorn",
  "back.png": "I Am Back",
  "hood.jpg": "Hooded",
  "tree.png": "Tree of Life",
  "crackedFaces.png": "Fraction Agency",
  "sweets.png": "Sweets For The Sweet",
  "concrete_melting.png": "Melting Concrete",
  "hypocrites.png": "HypoChrist",
  "hose_face.png": "Hose Face",
  "turbine.png": "Comprehension",
  "comix_collection.png": "The Good Old Times",
  "time.png": "Time",
  "cannibal.png": "Ready When You Are",
  "food_chain.png": "Cross Dependencies",
  "outta_my_head.png": "Outta My Head",
  "cracked_lips.png": "A Cracked Smile",
  "human_land.png": "Pillars of Humiliation",
  "dead_god.jpg": "Rather Than Server In Heaven",
  "afterHours.jpg": "After Hours",
  "trout_on_ktm.jpg": "Trout On A Bike",
  "bloodQueen.jpg": "Blood Queen",
  "pokemongo.jpg": "PokeMongo",
  "bones.jpg": "Lie With Your Bones",
  "giveMeUrHand.jpg": "Give Me Your Hand",
  "hug.jpg": "Hug The Perversion",
  "longVisage.jpg": "Long Visage",
  "cyborgReaper3.jpg": "Ready",
  "girlAndMonstersX.jpg":"Me And My Monsters",
  "goForAWalk.jpg": "Go For A Walk",
  "fatSoldier.jpg": "Fat Soldier",
  "blackGirl.jpg": "Let It Pee",
  "cypork.jpg": "CyPork",
  "fairy.jpg": "Raise",
  "surrealWall.jpg": "Wall Of Insanity",
  "priest.jpg": "God Is With You",
  "phone.jpg": "Always Online",
  "spell.jpg": "The Spell",
  "violentine.jpg": "Happy Violentine's Day",
  "creep.jpg": "Freedom Of Expression",
  "maggots.jpg": "King Of Maggots",
  "spikehead.jpg": "Spikehead",
  "cyborgReaper2a.jpg": "Impending Mischief",
  "zombies.jpg": "Bad Situation",
  "lovers.jpg": "Empty Lovers", 
  "antlersface.jpg": "Antlered Face",
  "fireball.jpg": "Small Miracle",
  "hair.jpg": "I Comb Your Hair",
  "musick.jpg": "Musick",
  "cyborgReaper.jpg": "I Got Souls",
  "conjured.jpg": "Cold Impression",
  "rockStar.jpg": "Hit The Tone",
  "xMess.jpg": "X-Mess",
  "twoSwords.jpg": "Two Swords",
  "heIsTurningBlue.jpg": "He Is Turning Blue",
  "toothFairy.jpg": "Terry The Fairy",
  "yolandi.jpg": "Freeky",
  "phiBot.jpg": "Phi-Bot",
  "greenImp.jpg": "Cozy Bushy Green",
  "whiteCyborg.jpg": "Synthetic Pale",
  "sunDevourer.jpg": "Sun Devourer",
  "barAside.jpg": "Bar Aside",
  "psychoGirls_all.jpg": "My Little Girls",
  "psychoGirl.jpg": "Insane Madeleine",
  "mAz.jpg": "Can I Keep him, Mom?",
  "djMike_v1.4.jpg": "Groove Monsters",
  "sculptured.jpg": "Sculptured",
  "Stairs.jpg": "Punish The Innocent",
  "Mage.jpg": "The Mage Apprentice",
  "Street.jpg": "Attention! High Voltage",
  "shout.jpg": "Post Light",
  "fleshmountains.jpg": "Carnal Path",
  "beautiful.jpg": "The Pretty Ones",
  "angelEyes.jpg": "Eyes Of A Fallen Angel",
  "necro.jpg": "Ipasou",
  "7sins.jpg": "Sins",
  "ugly.jpg": "Aren't We Beautiful?",
  "planets.jpg": "Draining Planets",
  "bridge2.jpg": "The Bridge",
  "landescape.jpg": "Foreign Landescape",
  "puke.jpg": "Conema (Commercial Enema)",
  "lizardOnTheRock.jpg": "Step Through A Strange World",
  "teeth.jpg": "Cleft Lip",
  "Contract.jpg": "The Contract",
  "Spoteye.jpg": "Spoteye",
  "Reaper.jpg": "Eulogy",
  "Mimic.jpg": "Mimic"
};

export const imgData = [
  "unicorn.png",
  "back.png",
  "hood.jpg",
  "tree.png",
  "crackedFaces.png",
  "sweets.png",
  "concrete_melting.png",
  "hypocrites.png",
  "hose_face.png",
  "turbine.png",
  "comix_collection.png",
  "time.png",
  "cannibal.png",
  "food_chain.png",
  "outta_my_head.png",
  "cracked_lips.png",
  "human_land.png",
  "dead_god.jpg",
  "afterHours.jpg",
  "trout_on_ktm.jpg",
  "bloodQueen.jpg",
  "pokemongo.jpg",
  "bones.jpg",
  "giveMeUrHand.jpg",
  "hug.jpg",
  "longVisage.jpg",
  "cyborgReaper3.jpg",
  "girlAndMonstersX.jpg",
  "goForAWalk.jpg",
  "fatSoldier.jpg",
  "blackGirl.jpg",
  "cypork.jpg",
  "fairy.jpg",
  "surrealWall.jpg",
  "priest.jpg",
  "phone.jpg",
  "spell.jpg",
  "violentine.jpg",
  "creep.jpg",
  "maggots.jpg",
  "spikehead.jpg",
  "cyborgReaper2a.jpg",
  "zombies.jpg",
  "lovers.jpg",
  "antlersface.jpg",
  "fireball.jpg",
  "hair.jpg",
  "musick.jpg",
  "cyborgReaper.jpg",
  "conjured.jpg",
  "rockStar.jpg",
  "xMess.jpg",
  "twoSwords.jpg",
  "heIsTurningBlue.jpg",
  "toothFairy.jpg",
  "yolandi.jpg",
  "phiBot.jpg",
  "greenImp.jpg",
  "whiteCyborg.jpg",
  "sunDevourer.jpg",
  "barAside.jpg",
  "psychoGirls_all.jpg",
  "psychoGirl.jpg",
  "mAz.jpg",
  "djMike_v1.4.jpg",
  "sculptured.jpg",
  "Stairs.jpg",
  "Mage.jpg",
  "Street.jpg",
  "shout.jpg",
  "fleshmountains.jpg",
  "beautiful.jpg",
  "angelEyes.jpg",
  "necro.jpg",
  "7sins.jpg",
  "ugly.jpg",
  "planets.jpg",
  "bridge2.jpg",
  "landescape.jpg",
  "puke.jpg",
  "lizardOnTheRock.jpg",
  "teeth.jpg",
  "Contract.jpg",
  "Spoteye.jpg",
  "Reaper.jpg",
  "Mimic.jpg",
];
